name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-contract:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Foundry
      run: |
        make install-foundry
        source ~/.bashrc
        foundryup
    - name: Test smart contract
      run: make test
